### ISSUE TITLE
App does not update with changes to data model

### ISSUE THREAD

**Issue by lopierra** [include-dcc/data_curator#4]
**Describe the bug**
I made changes to the [data model](https://github.com/include-dcc/data-models), but the app did not update after I ran the deploy workflow.

**To Reproduce**
1. Make changes to data model (in this case, I changed Study Code "DS-Immune" to "BRI-DSR" and added "Component" to each template so the Synapse Tables would work properly)
2. Run GitHub Action - I first tried re-running the last tagged action ([v22.08.07](https://github.com/include-dcc/data_curator/actions/runs/2935922549)), and when that didn't work, I tried creating a new release ([v22.08.08](https://github.com/include-dcc/data_curator/actions/runs/3010896595)), which also didn't work.

**Expected behavior**
"DS-Immune" should have been replaced with "BRI-DSR" in all of the templates generated by the [app](https://www.synapse.org/#!Synapse:syn30109400).
I did not check the addition of Component yet - I assumed that was also not updated.

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [x] Critical 🆘

**Screenshots**
![image](https://user-images.githubusercontent.com/34149564/190212905-59c56420-d409-4640-87ee-05a1af690158.png)

**Desktop (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by afwillia** [comment]
@lopierra I fixed this for all versions of the app. The problem was that the branch `include-setup` branch was not up to date with the `develop` branch. I merged all of the include-specific setup code into the `main` and `develop` branches then deleted the extra branches to avoid future confusion.  I deployed the production app by tagging the main branch `v22.09.01`.
